name: Lint Code Base

on:
  push:
    branches: [ main, feature/ci-linting ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Run HTML Hint
      run: npx htmlhint "**/*.html"

    - name: Run ESLint
      run: npx eslint "public/js/**/*.js"

    - name: Run Stylelint
      run: npx stylelint "public/css/**/*.css"